///* =========================================================
// * ====                   WARNING                        ===
// * =========================================================
// * The code in this tab has been generated from the GUI form
// * designer and care should be taken when editing this file.
// * Only add/edit code inside the event handlers i.e. only
// * use lines between the matching comment tags. e.g.

// void myBtnEvents(GButton button) { //_CODE_:button1:12356:
//     // It is safe to enter your event code here  
// } //_CODE_:button1:12356:
 
// * Do not rename this tab!
// * =========================================================
// */

//public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:786529:
//  println("button1 - GButton >> GEvent." + event + " @ " + millis());
//  selectInput("Select a file to process:", "fileSelected");
//} //_CODE_:button1:786529:

//public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:703751:
//  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());
//} //_CODE_:textarea1:703751:



//// Create all the GUI controls. 
//// autogenerated do not edit
//public void createGUI(){
//  G4P.messagesEnabled(false);
//  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
//  G4P.setCursor(ARROW);
//  surface.setTitle("Batik Bot");
//  button1 = new GButton(this, 16, 20, 168, 58);
//  button1.setText("Select CSV file");
//  button1.addEventHandler(this, "button1_click1");
//  textarea1 = new GTextArea(this, 200, 20, 250, 280, G4P.SCROLLBARS_NONE);
//  textarea1.setOpaque(true);
//  textarea1.addEventHandler(this, "textarea1_change1");
//}

//// Variable declarations 
//// autogenerated do not edit
//GButton button1; 
//GTextArea textarea1; 
